trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- bash: git clone --depth 1 https://github.com/python/cpython.git
  displayName: 'Fetch CPython master branch'

- bash: |
    set -e
    echo "deb-src http://archive.ubuntu.com/ubuntu/ bionic main restricted" | sudo tee -a /etc/apt/sources.list
    echo "deb-src http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted" | sudo tee -a /etc/apt/sources.list
    sudo apt update
    sudo apt build-dep python3.6
  displayName: 'Install CPython build dependencies for Ubuntu 18.04'

- bash: |
    set -e
    WORKDIR=`pwd`
    pushd cpython
    ./configure --prefix $WORKDIR/cpython-nightly --with-lto
    make -j4
    make install
    popd
  displayName: 'Configure and build CPython'

- bash: ./cpython-nightly/bin/python -m pip install -U pip setuptools
  displayName: 'Update pip and setuptools'

- bash: tar cf cpython-nightly.tar.xz cpython-nightly
  displayName: 'Prepare compressed archive'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'cpython-nightly.tar.xz'
    artifact: 'cpython-nightly.tar.xz'
    publishLocation: 'pipeline'
