trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
# - bash: git clone --depth 1 https://github.com/python/cpython.git
#   displayName: 'Fetch CPython master branch'

# - bash: |
#     set -e
#     echo "deb-src http://archive.ubuntu.com/ubuntu/ bionic main restricted" | sudo tee -a /etc/apt/sources.list
#     echo "deb-src http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted" | sudo tee -a /etc/apt/sources.list
#     sudo apt update
#     sudo apt build-dep python3.6
#   displayName: 'Install CPython build dependencies for Ubuntu 18.04'

# - bash: |
#     set -e
#     WORKDIR=`pwd`
#     pushd cpython
#     ./configure --prefix $WORKDIR/cpython-nightly --with-lto
#     make -j4
#     make install
#     popd
#   displayName: 'Configure and build CPython'

# - bash: |
#     set -e
#     pushd cpython-nightly/bin
#     ln -s python3 python
#     ./python -m pip install -U pip setuptools
#     popd
#   displayName: 'Symlink python3 to python, update pip and setuptools'

- bash: mkdir cpython-nightly
  displayName: 'Prepare empty test folder'

- bash: tar cf cpython-nightly.tar.xz cpython-nightly
  displayName: 'Prepare compressed archive'

- bash: |
    set -e
    echo "##vso[task.prependpath]$CONDA/bin"
    sudo chown -R $USER $CONDA
  displayName: Add conda to PATH

- bash: conda install -q -y anaconda-client
  displayName: Install anaconda-client

- bash: |
    anaconda -t $TOKEN upload
      --force -u ogrisel -t file -p cpython-nightly -v nightly \
      -d "CPython nightly build" \
      -s "CPython nightly build" \
      cpython-nightly.tar.xz
  displayName: Upload to anaconda.org
  env:
    # Secret variables need to mapped to env variables explicitly:
    TOKEN: $(CPYTHON_NIGHTLY_UPLOAD_TOKEN)
