trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- bash: git clone --depth 1 https://github.com/python/cpython.git
  displayName: 'git clone cpython master branch'

- bash: apt build-dep python3.6
  displayName: 'Install CPython build dependeices for Ubuntu 16.04'

- bash: |
    set -e
    pushd cpython
    ./configure --prefix $PIPELINE_WORKSPACE/cpython-nightly --with-lto
    make -j4
    make install
    popd
  displayName: 'Install CPython build dependeices for Ubuntu 16.04'

- bash: ./cpython-nightly/bin/python -m pip install -U pip setuptools
  displayName: 'Update pip and setuptools'

- bash: |
    set -e
    tar cf cpython-nightly.tar.xz cpython-nightly
  displayName: 'Prepare compressed archive'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'cpython-nightly.tar.xz'
    publishLocation: 'pipeline'
