trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
# - bash: git clone --depth 1 https://github.com/python/cpython.git
#   displayName: 'Fetch CPython master branch'

# - bash: |
#     set -e
#     echo "deb-src http://archive.ubuntu.com/ubuntu/ bionic main restricted" | sudo tee -a /etc/apt/sources.list
#     echo "deb-src http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted" | sudo tee -a /etc/apt/sources.list
#     sudo apt update
#     sudo apt build-dep python3.6
#   displayName: 'Install CPython build dependencies for Ubuntu 18.04'

# - bash: |
#     set -e
#     WORKDIR=`pwd`
#     pushd cpython
#     ./configure --prefix $WORKDIR/cpython-nightly --with-lto
#     make -j4
#     make install
#     popd
#   displayName: 'Configure and build CPython'

# - bash: |
#     set -e
#     pushd cpython-nightly/bin
#     ln -s python3 python
#     ./python -m pip install -U pip setuptools
#     popd
#   displayName: 'Symlink python3 to python, update pip and setuptools'

- bash: mkdir cpython-nightly
  displayName: 'Prepare empty test folder'

- bash: tar cf cpython-nightly.tar.xz cpython-nightly
  displayName: 'Prepare compressed archive'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'ogrisel'
    repositoryName: '$(Build.Repository.Name)'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: 'nightly'
    title: 'Nightly build of CPython master branch'
    releaseNotesSource: 'inline'
    releaseNotesInline: 'This archive is updated every night around 2 AM UTC. It should work with Ubuntu 18.04 on amd64.'
    assets: '$(System.DefaultWorkingDirectory)/*.tar.xz'
    assetUploadMode: 'replace'
    isPreRelease: true
    addChangeLog: false